docs: version-9 번역
luciancah/nextjs-ko pull request #101
Opened 2024-08-05 01:26 UTC by mini-boo

**컨트리뷰션 체크리스트**

- [x] [기여 가이드](https://github.com/luciancah/nextjs-ko/blob/main/CONTRIBUTING.MD)를 확인한 후 작성 하셨나요?
- [x] [용어집](https://github.com/luciancah/nextjs-ko/issues/18)을 확인한 후 작성 하셨나요? 번역하신 단어 중 용어집에 추가하고싶은 단어가 있으시다면 이슈에 댓글로 남겨주세요.
- [x] title, description 등 마크다운 태그의 영문 원본 유지를 하셨나요?
- [x] 소제목 (h1~h6, ### ... 등)의 영문 유지를 하셨나요?
- [x] 문서의 전반적인 어조 톤과 일치하게 작성 하셨나요?
- [x] 코드블록 내부의 주석이나 업데이트 로그 등 표 내부의 문자도 한국어로 번역 하셨나요?

**연관된 이슈 확인**

closes #90 

**기여 내용**

- [x] 새로운 문서 번역
- [ ] 문서 내용 수정
- [ ] 오타 수정
- [ ] 문서 웹페이지 기능 수정
- [ ] 기타 기능 개선 및 수정

**문서 경로**

/docs/pages/building-your-application/upgrading/version-9.mdx

2024-08-05 02:21 UTC, luciancah requested changes
안녕하세요, 프로젝트 파일 삭제는 원본 gitignore 수정하지 않는 선에서 부탁드리겠습니다. 수정 사항은 새 pr 여실 필요 없습니다 :)

2024-08-05 08:52 UTC, mini-boo commented
번역 파일 하나만 pr하면 될 걸 모두 pr해버리는 바람에 사단이 났네요.. 일단 새롭게 생성되는 의존성 파일들은 모두 삭제하여 커밋했습니다 ㅜㅜ

2024-08-05 11:28 UTC, luciancah requested changes
안녕하세요, 일부 문서 컨벤션에 맞지 않아 보이는 부분이 있어 확인 부탁드리겠습니다.

2024-08-05 11:28 UTC, luciancah commented on pages/docs/pages/building-your-application/upgrading/version-9.mdx
> +버전 `9` 로 업그레이드하려면 아래의 명령어를 실행하세요:
인라인 코드 사용의 원문 유지 부탁드립니다.

2024-08-05 11:28 UTC, luciancah commented on pages/docs/pages/building-your-application/upgrading/version-9.mdx
> +과거에 vercel.json 파일에서 동적 경로를 위해 routes를 구성했다면, Next.js 9의 새로운 기능인 [Dynamic Routing feature](/docs/pages/building-your-application/routing/dynamic-routes)을 활용해 이러한 규칙을 제거할 수 있습니다.
인라인 코드 사용의 원문 유지 부탁드립니다.

2024-08-05 11:28 UTC, luciancah commented on pages/docs/pages/building-your-application/upgrading/version-9.mdx
> +마이그레이션을 수동으로 수행하거나, 코드 변환기의 생성 결과를 보려면 아래를 참조하세요:
[codemod](https://nextjs-ko.org/docs/app/building-your-application/upgrading/codemods)의 코드 변환기로의 번역이 필요하지 않아 보이는데, 어떻게 생각하세요?

2024-08-05 23:59 UTC, mini-boo commented on pages/docs/pages/building-your-application/upgrading/version-9.mdx
> +버전 `9` 로 업그레이드하려면 아래의 명령어를 실행하세요:
수정했습니다!

2024-08-06 00:00 UTC, mini-boo commented on pages/docs/pages/building-your-application/upgrading/version-9.mdx
> +과거에 vercel.json 파일에서 동적 경로를 위해 routes를 구성했다면, Next.js 9의 새로운 기능인 [Dynamic Routing feature](/docs/pages/building-your-application/routing/dynamic-routes)을 활용해 이러한 규칙을 제거할 수 있습니다.
수정했습니다!

2024-08-06 00:00 UTC, mini-boo commented on pages/docs/pages/building-your-application/upgrading/version-9.mdx
> +마이그레이션을 수동으로 수행하거나, 코드 변환기의 생성 결과를 보려면 아래를 참조하세요:
제안 감사합니다 :) 내용을 바탕으로 수정했습니다!

2024-08-07 09:36 UTC, luciancah requested changes
안녕하세요, 수정 감사합니다.
죄송하지만 기여 가이드에 맞춰서 전반적인 작업 내용 검토 부탁드려도 될까요? 제가 리뷰에서 한번에 모든 항목을 검수 할 수 없는 점 양해 부탁드립니다.
추가로 문서 포맷팅에도 문제가 있는 것으로 보여서 `pnpm run format:fix` 실행 후 커밋 부탁드리겠습니다.

2024-08-07 09:36 UTC, luciancah commented on pages/docs/pages/building-your-application/upgrading/version-9.mdx
> -Next.js 9's dynamic routes are **automatically configured on [Vercel](https://vercel.com/)** and do not require any `vercel.json` customization.
이쪽 인라인 코드 문법 수정도 확인 부탁드립니다.

2024-08-08 07:08 UTC, mini-boo commented
기여 문서 다시 한번 확인하여 최종 수정하였고, gpt를 통해 검수 마쳤습니다. 더불어 문서 포맷팅도 완료했습니다.

감사합니다!

2024-08-09 10:42 UTC, luciancah approved these changes
오랜 시간 고생하셨습니다 :)

2024-08-11 09:31 UTC, merged