[#84] docs: getStaticProps 번역
luciancah/nextjs-ko pull request #106
Opened 2024-08-05 08:47 UTC by grapefruit13

**컨트리뷰션 체크리스트**

- [x] [기여 가이드](https://github.com/luciancah/nextjs-ko/blob/main/CONTRIBUTING.MD)를 확인한 후 작성 하셨나요?
- [x] [용어집](https://github.com/luciancah/nextjs-ko/issues/18)을 확인한 후 작성 하셨나요? 번역하신 단어 중 용어집에 추가하고싶은 단어가 있으시다면 이슈에 댓글로 남겨주세요.
- [x] title, description 등 마크다운 태그의 영문 원본 유지를 하셨나요?
- [x] 소제목 (h1~h6, ### ... 등)의 영문 유지를 하셨나요?
- [x] 문서의 전반적인 어조 톤과 일치하게 작성 하셨나요?
- [x] 코드블록 내부의 주석이나 업데이트 로그 등 표 내부의 문자도 한국어로 번역 하셨나요?

**연관된 이슈 확인**

closes #84 

**기여 내용**

- [ ] 새로운 문서 번역
- [ ] 문서 내용 수정
- [ ] 오타 수정
- [ ] 문서 웹페이지 기능 수정
- [ ] 기타 기능 개선 및 수정

**문서 경로**

2024-08-05 11:31 UTC, luciancah requested changes
<img width="862" alt="image" src="https://github.com/user-attachments/assets/0a99712a-a3f5-46c6-9fc5-453829eeed2a">

확인 부탁드리겠습니다 :)

2024-08-07 08:20 UTC, grapefruit13 commented
@luciancah 
코멘트를 이제야 확인하였네요 😅
context parameter 표부분 제대로 나오도록 수정했습니다. 
![image](https://github.com/user-attachments/assets/d6709531-1b91-4c7f-8292-4e510d387e5d)

2024-08-07 09:47 UTC, luciancah requested changes
안녕하세요, 기여 감사합니다. 문서 중 어색하다고 느껴질 수 있는 부분이 몇 가지 있어서 짧게 코멘트 드립니다. 확인 부탁드리겠습니다 :)

2024-08-07 09:47 UTC, luciancah commented on pages/docs/pages/api-reference/functions/get-static-props.mdx
>  If the redirects are known at build-time, they should be added in [`next.config.js`](/docs/pages/api-reference/next-config-js/redirects) instead.
원본 내용이 삭제되지 않은 것으로 보입니다.

2024-08-07 09:47 UTC, luciancah commented on pages/docs/pages/api-reference/functions/get-static-props.mdx
> +[증분 정적 재생성](/docs/pages/building-your-application/data-fetching/incremental-static-regeneration)에 대해 자세히 알아보세요.
[ISR](https://nextjs-ko.org/docs/pages/building-your-application/data-fetching/incremental-static-regeneration)문서에서 사용하듯이 ISR에 대한 항목은 증분 정적 재생성으로의 번역이 필요하지 않은 것으로 보입니다. 이곳 이외에도 다른 위치에서 등장하는 부분들에 대해서도 같이 수정 부탁드리겠습니다!

2024-08-07 10:53 UTC, grapefruit13 commented on pages/docs/pages/api-reference/functions/get-static-props.mdx
> +[증분 정적 재생성](/docs/pages/building-your-application/data-fetching/incremental-static-regeneration)에 대해 자세히 알아보세요.
네 수정하였습니다!

2024-08-07 15:01 UTC, luciancah approved these changes
감사합니다 :) 다음 정기 배포에 맞추어 머지하겠습니다.

2024-08-11 09:32 UTC, merged