[#105] docs: amp 번역
luciancah/nextjs-ko pull request #107
Opened 2024-08-05 09:26 UTC by Ubinquitous

**컨트리뷰션 체크리스트**

- [x] [기여 가이드](https://github.com/luciancah/nextjs-ko/blob/main/CONTRIBUTING.MD)를 확인한 후 작성 하셨나요?
- [x] [용어집](https://github.com/luciancah/nextjs-ko/issues/18)을 확인한 후 작성 하셨나요? 번역하신 단어 중 용어집에 추가하고싶은 단어가 있으시다면 이슈에 댓글로 남겨주세요.
- [x] title, description 등 마크다운 태그의 영문 원본 유지를 하셨나요?
- [x] 소제목 (h1~h6, ### ... 등)의 영문 유지를 하셨나요?
- [x] 문서의 전반적인 어조 톤과 일치하게 작성 하셨나요?
- [x] 코드블록 내부의 주석이나 업데이트 로그 등 표 내부의 문자도 한국어로 번역 하셨나요?

**연관된 이슈 확인**

closes #105 

**기여 내용**

- [x] 새로운 문서 번역
- [ ] 문서 내용 수정
- [ ] 오타 수정
- [ ] 문서 웹페이지 기능 수정
- [ ] 기타 기능 개선 및 수정

**문서 경로**

/docs/pages/building-your-application/configuring/amp.mdx

2024-08-05 11:40 UTC, Ubinquitous commented
앗핫 제가 착각했네요 죄송합니다!!
다시 파일 이동 완료했습니다!

2024-08-07 09:51 UTC, luciancah requested changes
안녕하세요, 기여 감사합니다! 문서 전반적인 스타일 확인 리뷰 부탁드리겠습니다 :)

2024-08-08 06:28 UTC, luciancah requested changes
안녕하세요! 수정해주신 부분 잘 확인했습니다. 일부 덜 수정된 부분이 보여서 다시 코멘트 드립니다. 1회 리뷰에 전체 문서를 검수하기 조금 힘든 부분이 있어서, 양해 부탁드리겠습니다.

2024-08-08 06:28 UTC, luciancah commented on pages/docs/pages/building-your-application/configuring/amp.mdx
> +- out/about/index.html - HTML 페이지
인라인 코드 확인 부탁드립니다.

2024-08-09 10:43 UTC, luciancah approved these changes
고생하셨습니다 :) 기여 감사합니다 !

2024-08-11 09:32 UTC, merged