[#115] docs: image-regacy 번역
luciancah/nextjs-ko pull request #116
Opened 2024-08-06 13:53 UTC by wlstmd

**컨트리뷰션 체크리스트**

- [x] [기여 가이드](https://github.com/luciancah/nextjs-ko/blob/main/CONTRIBUTING.MD)를 확인한 후 작성 하셨나요?
- [x] [용어집](https://github.com/luciancah/nextjs-ko/issues/18)을 확인한 후 작성 하셨나요? 번역하신 단어 중 용어집에 추가하고싶은 단어가 있으시다면 이슈에 댓글로 남겨주세요.
- [x] title, description 등 마크다운 태그의 영문 원본 유지를 하셨나요?
- [x] 소제목 (h1~h6, ### ... 등)의 영문 유지를 하셨나요?
- [x] 문서의 전반적인 어조 톤과 일치하게 작성 하셨나요?
- [x] 코드블록 내부의 주석이나 업데이트 로그 등 표 내부의 문자도 한국어로 번역 하셨나요?

**연관된 이슈 확인**

closes #115 

**기여 내용**

- [x] 새로운 문서 번역
- [ ] 문서 내용 수정
- [ ] 오타 수정
- [ ] 문서 웹페이지 기능 수정
- [ ] 기타 기능 개선 및 수정

**문서 경로**

/docs/pages/api-reference/components/image-legacy.mdx

2024-08-07 10:03 UTC, luciancah approved these changes
안녕하세요! 기여 감사합니다. 다음 정기 배포에 맞춰서 머지하겠습니다 :)

2024-08-07 10:04 UTC, luciancah requested changes
미처 확인 못한 부분이 있었네요! h1 이하 모든 heading(#, ## ... ) 영문 유지 부탁드립니다 :)

2024-08-07 10:04 UTC, luciancah commented on pages/docs/pages/api-reference/components/image-legacy.mdx
> -## Comparison
headings 영문 유지 부탁드립니다 !! 밑에도 동일입니다.

2024-08-07 10:50 UTC, wlstmd commented on pages/docs/pages/api-reference/components/image-legacy.mdx
> -## Comparison
아아 맞네요... 수정하겠습니다!

2024-08-07 10:57 UTC, wlstmd commented on pages/docs/pages/api-reference/components/image-legacy.mdx
> -## Comparison
수정 했습니다!

2024-08-08 06:35 UTC, luciancah approved these changes
기여 감사합니다 :) 다음 정기 배포에 맞추어 머지하겠습니다.

2024-08-11 09:43 UTC, merged