[#34] docs: get-static-paths 번역
luciancah/nextjs-ko pull request #35
Opened 2024-07-26 09:20 UTC by gkfyr

`PR를 작성하시기 전에 [기여 가이드[(https://nextjs-ko.org/contribution)을 먼저 확인해주세요.`

**컨트리뷰션 체크리스트**

- [x] 기여 가이드를 확인한 후 작성 하셨나요?
- [x] title, description 등 마크다운 태그의 영문 원본 유지를 하셨나요?
- [x] 소제목 (h1~h6)의 영문 유지를 하셨나요?
- [x] 문서의 전반적인 어조 톤과 일치하게 작성 하셨나요?
- [x] 코드블록 내부의 주석이나 업데이트 로그 등 표 내부의 문자도 한국어로 번역 하셨나요?

**연관된 이슈 확인**
 closes #34

**기여 내용**

- [x] 새로운 문서 번역
- [ ] 문서 내용 수정
- [ ] 오타 수정
- [ ] 문서 웹페이지 기능 수정
- [ ] 기타 기능 개선 및 수정

**문서 경로**
`/docs/pages/building-your-application/data-fetching/get-static-paths.mdx`

2024-07-26 14:48 UTC, luciancah requested changes
안녕하세요! 기여 감사합니다. [가이드](https://github.com/luciancah/nextjs-ko/blob/main/CONTRIBUTING.MD#2-%EB%AC%B8%EC%84%9C-%EB%82%B4%EB%B6%80%EC%9D%98-heading)에 맞춰 번역하신 내용 중 heading들 (##, ###, ... ) 영어 원문 유지 부탁드리겠습니다!

2024-07-26 14:48 UTC, luciancah commented on pages/docs/pages/building-your-application/data-fetching/get-static-paths.mdx
> +## getStaticPaths를 언제 사용해야 하나요?
안녕하세요! 기여 감사합니다. [가이드](https://github.com/luciancah/nextjs-ko/blob/main/CONTRIBUTING.MD#2-%EB%AC%B8%EC%84%9C-%EB%82%B4%EB%B6%80%EC%9D%98-heading)에 맞춰 번역하신 내용 중 heading들 (##, ###, ... ) 영어 원문 유지 부탁드리겠습니다!

2024-07-27 17:17 UTC, gkfyr commented on pages/docs/pages/building-your-application/data-fetching/get-static-paths.mdx
> +## getStaticPaths를 언제 사용해야 하나요?
@luciancah 죄송합니다. 가이드 내용 이해에 착오가 있었던 모양입니다. 원문으로 수정해서 푸쉬 완료했습니다.

2024-07-28 08:06 UTC, luciancah approved these changes
감사합니다, 잘 확인했습니다! ☺️ 이제 막 시작한 프로젝트이다 보니, 현재 보내주신 PR은 다른 분들께서 기여를 시작하실때 참고하실 수 있도록 일정 기간 유지(1주일 이내) 후 머지하도록 하겠습니다.

2024-07-31 05:30 UTC, merged