[#46] docs: version-13 번역
luciancah/nextjs-ko pull request #47
Opened 2024-07-28 16:33 UTC by hansololiviakim

**컨트리뷰션 체크리스트**

- [x] [기여 가이드](https://github.com/luciancah/nextjs-ko/blob/main/CONTRIBUTING.MD)를 확인한 후 작성 하셨나요?
- [x] [용어집](https://github.com/luciancah/nextjs-ko/issues/18)을 확인한 후 작성 하셨나요? 번역하신 단어 중 용어집에 추가하고싶은 단어가 있으시다면 이슈에 댓글로 남겨주세요.
- [x] title, description 등 마크다운 태그의 영문 원본 유지를 하셨나요?
- [x] 소제목 (h1~h6, ### ... 등)의 영문 유지를 하셨나요?
- [x] 문서의 전반적인 어조 톤과 일치하게 작성 하셨나요?
- [x] 코드블록 내부의 주석이나 업데이트 로그 등 표 내부의 문자도 한국어로 번역 하셨나요?

**연관된 이슈 확인**
closes #46 

**기여 내용**

- [x] 새로운 문서 번역
- [ ] 문서 내용 수정
- [ ] 오타 수정
- [ ] 문서 웹페이지 기능 수정
- [ ] 기타 기능 개선 및 수정

**문서 경로**
/docs/pages/building-your-application/upgrading/version-13

2024-07-29 01:49 UTC, luciancah requested changes
`ReferenceError: img is not defined` 발생합니다!
아마 mdx 파일 안에서 작성해주신 <Image /> 컴포넌트를 렌더하려고 시도한 것으로 보입니다.
`<Image src={img} />` 등으로 작성해주세요!

2024-07-29 01:49 UTC, luciancah commented on pages/docs/pages/building-your-application/upgrading/version-13.mdx
> +- [next-image-experimental](/docs/pages/building-your-application/upgrading/codemods#next-image-experimental): 이전 codemod를 실행한 후, 이 실험적인 codemod를 선택적으로 실행하여 `next/legacy/image`를 새로운 `next/image`로 업그레
이미지 태그 `코드`로 감싸주세요!

2024-07-29 15:37 UTC, hansololiviakim commented on pages/docs/pages/building-your-application/upgrading/version-13.mdx
> +- [next-image-experimental](/docs/pages/building-your-application/upgrading/codemods#next-image-experimental): 이전 codemod를 실행한 후, 이 실험적인 codemod를 선택적으로 실행하여 `next/legacy/image`를 새로운 `next/image`로 업그레
수정했습니다! 감사합니다 :)

2024-07-30 05:01 UTC, luciancah approved these changes
안녕하세요, 기여 감사합니다! ☺️ 이제 막 시작한 프로젝트이다 보니, 현재 보내주신 PR은 다른 분들께서 기여를 시작하실때 참고하실 수 있도록 일정 기간 유지(일요일) 후 머지하도록 하겠습니다.

2024-07-31 05:32 UTC, merged